// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwLaf6H-YGTh52IXkCrITMLm-B9DmlHOk',
    appId: '1:552430236196:web:c286a6eb2bdccf320cdeb1',
    messagingSenderId: '552430236196',
    projectId: 'fir-164a2',
    authDomain: 'fir-164a2.firebaseapp.com',
    storageBucket: 'fir-164a2.appspot.com',
    measurementId: 'G-CFG9VEQ2TT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWLGitDjjnL5WSQ0csjreLpRRnqtBIh80',
    appId: '1:552430236196:android:9143f525fac88d890cdeb1',
    messagingSenderId: '552430236196',
    projectId: 'fir-164a2',
    storageBucket: 'fir-164a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD38z45bVAX0zCCG8L5OUWcA6fCu8szy-E',
    appId: '1:552430236196:ios:bd21ea2681e9ae870cdeb1',
    messagingSenderId: '552430236196',
    projectId: 'fir-164a2',
    storageBucket: 'fir-164a2.appspot.com',
    iosClientId: '552430236196-81khgognj0rp10b4ij37uidh8mt39f89.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD38z45bVAX0zCCG8L5OUWcA6fCu8szy-E',
    appId: '1:552430236196:ios:bd21ea2681e9ae870cdeb1',
    messagingSenderId: '552430236196',
    projectId: 'fir-164a2',
    storageBucket: 'fir-164a2.appspot.com',
    iosClientId: '552430236196-81khgognj0rp10b4ij37uidh8mt39f89.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );
}
